language: go

go:
  - 1.4.2
  - 1.5
  - 1.6
  - 1.7
  - tip

services:
  - redis-server

before_install:

install:
  - go get github.com/gomodule/redigo/redis
  - go get github.com/northbright/redishelper
