language: go

go:
  - 1.3.3
  - 1.4.2
  - 1.5
  - 1.6
  - 1.7
  - tip

before_install:
  - ./install-and-run-redis.sh

install:
  - go get github.com/garyburd/redigo/redis
  - go get github.com/northbright/redishelper
